changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - weblate
  categories:
    - title: What's New
      labels:
        - enhancement
    - title: Fixed
      labels:
        - bug
    - title: Other Changes
      labels:
        - "*"
